// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.11
// source: cs_common.proto

package cs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息头
type CsHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd int32 `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Seq int32 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Ret int32 `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
}

func (x *CsHead) Reset() {
	*x = CsHead{}
	mi := &file_cs_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsHead) ProtoMessage() {}

func (x *CsHead) ProtoReflect() protoreflect.Message {
	mi := &file_cs_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsHead.ProtoReflect.Descriptor instead.
func (*CsHead) Descriptor() ([]byte, []int) {
	return file_cs_common_proto_rawDescGZIP(), []int{0}
}

func (x *CsHead) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *CsHead) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *CsHead) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

// 消息包
type CsPkg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *CsHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Body []byte  `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *CsPkg) Reset() {
	*x = CsPkg{}
	mi := &file_cs_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsPkg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsPkg) ProtoMessage() {}

func (x *CsPkg) ProtoReflect() protoreflect.Message {
	mi := &file_cs_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsPkg.ProtoReflect.Descriptor instead.
func (*CsPkg) Descriptor() ([]byte, []int) {
	return file_cs_common_proto_rawDescGZIP(), []int{1}
}

func (x *CsPkg) GetHead() *CsHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *CsPkg) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// 错误码通知
type CsCmdNtfErrorCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd     int32 `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	ErrCode int32 `protobuf:"varint,2,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
}

func (x *CsCmdNtfErrorCode) Reset() {
	*x = CsCmdNtfErrorCode{}
	mi := &file_cs_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsCmdNtfErrorCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCmdNtfErrorCode) ProtoMessage() {}

func (x *CsCmdNtfErrorCode) ProtoReflect() protoreflect.Message {
	mi := &file_cs_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCmdNtfErrorCode.ProtoReflect.Descriptor instead.
func (*CsCmdNtfErrorCode) Descriptor() ([]byte, []int) {
	return file_cs_common_proto_rawDescGZIP(), []int{2}
}

func (x *CsCmdNtfErrorCode) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *CsCmdNtfErrorCode) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

var File_cs_common_proto protoreflect.FileDescriptor

var file_cs_common_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x63, 0x73, 0x22, 0x3e, 0x0a, 0x06, 0x43, 0x73, 0x48, 0x65, 0x61, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x6d,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x73, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x72, 0x65, 0x74, 0x22, 0x3b, 0x0a, 0x05, 0x43, 0x73, 0x50, 0x6b, 0x67, 0x12, 0x1e,
	0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x63,
	0x73, 0x2e, 0x43, 0x73, 0x48, 0x65, 0x61, 0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x22, 0x40, 0x0a, 0x11, 0x43, 0x73, 0x43, 0x6d, 0x64, 0x4e, 0x74, 0x66, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x72, 0x72,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x72, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x63, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cs_common_proto_rawDescOnce sync.Once
	file_cs_common_proto_rawDescData = file_cs_common_proto_rawDesc
)

func file_cs_common_proto_rawDescGZIP() []byte {
	file_cs_common_proto_rawDescOnce.Do(func() {
		file_cs_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_cs_common_proto_rawDescData)
	})
	return file_cs_common_proto_rawDescData
}

var file_cs_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cs_common_proto_goTypes = []any{
	(*CsHead)(nil),            // 0: cs.CsHead
	(*CsPkg)(nil),             // 1: cs.CsPkg
	(*CsCmdNtfErrorCode)(nil), // 2: cs.CsCmdNtfErrorCode
}
var file_cs_common_proto_depIdxs = []int32{
	0, // 0: cs.CsPkg.head:type_name -> cs.CsHead
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cs_common_proto_init() }
func file_cs_common_proto_init() {
	if File_cs_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cs_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cs_common_proto_goTypes,
		DependencyIndexes: file_cs_common_proto_depIdxs,
		MessageInfos:      file_cs_common_proto_msgTypes,
	}.Build()
	File_cs_common_proto = out.File
	file_cs_common_proto_rawDesc = nil
	file_cs_common_proto_goTypes = nil
	file_cs_common_proto_depIdxs = nil
}
