// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.11
// source: cs_error_code.proto

package cs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ERR_CODE int32

const (
	ERR_CODE_UNKNOW  ERR_CODE = 0
	ERR_CODE_SUCCESS ERR_CODE = 1
	ERR_CODE_FAILED  ERR_CODE = 2
	// login
	ERR_CODE_LOGIN_FAILED          ERR_CODE = 101 // 登录失败
	ERR_CODE_LOGIN_INVALID_ACCOUNT ERR_CODE = 102 // 无效的账号
	ERR_CODE_LOGIN_ONLINE          ERR_CODE = 103 // 账号已在线
	ERR_CODE_LOGIN_NEED_CREATE     ERR_CODE = 104 // 需要创建账号
	ERR_CODE_CREATE_ACCOUNT_FAILED ERR_CODE = 105 // 创建账号失败
	ERR_CODE_KICKED                ERR_CODE = 106 // 被踢下线
	ERR_CODE_CREATE_EXITE_ACCOUNT  ERR_CODE = 107 // 已经存在的账号
)

// Enum value maps for ERR_CODE.
var (
	ERR_CODE_name = map[int32]string{
		0:   "UNKNOW",
		1:   "SUCCESS",
		2:   "FAILED",
		101: "LOGIN_FAILED",
		102: "LOGIN_INVALID_ACCOUNT",
		103: "LOGIN_ONLINE",
		104: "LOGIN_NEED_CREATE",
		105: "CREATE_ACCOUNT_FAILED",
		106: "KICKED",
		107: "CREATE_EXITE_ACCOUNT",
	}
	ERR_CODE_value = map[string]int32{
		"UNKNOW":                0,
		"SUCCESS":               1,
		"FAILED":                2,
		"LOGIN_FAILED":          101,
		"LOGIN_INVALID_ACCOUNT": 102,
		"LOGIN_ONLINE":          103,
		"LOGIN_NEED_CREATE":     104,
		"CREATE_ACCOUNT_FAILED": 105,
		"KICKED":                106,
		"CREATE_EXITE_ACCOUNT":  107,
	}
)

func (x ERR_CODE) Enum() *ERR_CODE {
	p := new(ERR_CODE)
	*p = x
	return p
}

func (x ERR_CODE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ERR_CODE) Descriptor() protoreflect.EnumDescriptor {
	return file_cs_error_code_proto_enumTypes[0].Descriptor()
}

func (ERR_CODE) Type() protoreflect.EnumType {
	return &file_cs_error_code_proto_enumTypes[0]
}

func (x ERR_CODE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ERR_CODE.Descriptor instead.
func (ERR_CODE) EnumDescriptor() ([]byte, []int) {
	return file_cs_error_code_proto_rawDescGZIP(), []int{0}
}

var File_cs_error_code_proto protoreflect.FileDescriptor

var file_cs_error_code_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x73, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x63, 0x73, 0x2a, 0xc6, 0x01, 0x0a, 0x08, 0x45, 0x52,
	0x52, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x4c,
	0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x65, 0x12, 0x19, 0x0a,
	0x15, 0x4c, 0x4f, 0x47, 0x49, 0x4e, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x41,
	0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x10, 0x66, 0x12, 0x10, 0x0a, 0x0c, 0x4c, 0x4f, 0x47, 0x49,
	0x4e, 0x5f, 0x4f, 0x4e, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x67, 0x12, 0x15, 0x0a, 0x11, 0x4c, 0x4f,
	0x47, 0x49, 0x4e, 0x5f, 0x4e, 0x45, 0x45, 0x44, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10,
	0x68, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x5f, 0x41, 0x43, 0x43, 0x4f,
	0x55, 0x4e, 0x54, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x69, 0x12, 0x0a, 0x0a, 0x06,
	0x4b, 0x49, 0x43, 0x4b, 0x45, 0x44, 0x10, 0x6a, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x52, 0x45, 0x41,
	0x54, 0x45, 0x5f, 0x45, 0x58, 0x49, 0x54, 0x45, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54,
	0x10, 0x6b, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_cs_error_code_proto_rawDescOnce sync.Once
	file_cs_error_code_proto_rawDescData = file_cs_error_code_proto_rawDesc
)

func file_cs_error_code_proto_rawDescGZIP() []byte {
	file_cs_error_code_proto_rawDescOnce.Do(func() {
		file_cs_error_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_cs_error_code_proto_rawDescData)
	})
	return file_cs_error_code_proto_rawDescData
}

var file_cs_error_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cs_error_code_proto_goTypes = []any{
	(ERR_CODE)(0), // 0: cs.ERR_CODE
}
var file_cs_error_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cs_error_code_proto_init() }
func file_cs_error_code_proto_init() {
	if File_cs_error_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cs_error_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cs_error_code_proto_goTypes,
		DependencyIndexes: file_cs_error_code_proto_depIdxs,
		EnumInfos:         file_cs_error_code_proto_enumTypes,
	}.Build()
	File_cs_error_code_proto = out.File
	file_cs_error_code_proto_rawDesc = nil
	file_cs_error_code_proto_goTypes = nil
	file_cs_error_code_proto_depIdxs = nil
}
