// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.11
// source: cs_login.proto

package cs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录请求
type CsCmdLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User     string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Platform string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
}

func (x *CsCmdLoginReq) Reset() {
	*x = CsCmdLoginReq{}
	mi := &file_cs_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsCmdLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCmdLoginReq) ProtoMessage() {}

func (x *CsCmdLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCmdLoginReq.ProtoReflect.Descriptor instead.
func (*CsCmdLoginReq) Descriptor() ([]byte, []int) {
	return file_cs_login_proto_rawDescGZIP(), []int{0}
}

func (x *CsCmdLoginReq) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CsCmdLoginReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

// 登录响应
type CsCmdLoginRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User      string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Platform  string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	AccountId uint64 `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *CsCmdLoginRes) Reset() {
	*x = CsCmdLoginRes{}
	mi := &file_cs_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsCmdLoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCmdLoginRes) ProtoMessage() {}

func (x *CsCmdLoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_cs_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCmdLoginRes.ProtoReflect.Descriptor instead.
func (*CsCmdLoginRes) Descriptor() ([]byte, []int) {
	return file_cs_login_proto_rawDescGZIP(), []int{1}
}

func (x *CsCmdLoginRes) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CsCmdLoginRes) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CsCmdLoginRes) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

// 登出请求
type CsCmdLoginOutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint64 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *CsCmdLoginOutReq) Reset() {
	*x = CsCmdLoginOutReq{}
	mi := &file_cs_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsCmdLoginOutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCmdLoginOutReq) ProtoMessage() {}

func (x *CsCmdLoginOutReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCmdLoginOutReq.ProtoReflect.Descriptor instead.
func (*CsCmdLoginOutReq) Descriptor() ([]byte, []int) {
	return file_cs_login_proto_rawDescGZIP(), []int{2}
}

func (x *CsCmdLoginOutReq) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

// 登出响应
type CsCmdLoginOutRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint64 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *CsCmdLoginOutRes) Reset() {
	*x = CsCmdLoginOutRes{}
	mi := &file_cs_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsCmdLoginOutRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCmdLoginOutRes) ProtoMessage() {}

func (x *CsCmdLoginOutRes) ProtoReflect() protoreflect.Message {
	mi := &file_cs_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCmdLoginOutRes.ProtoReflect.Descriptor instead.
func (*CsCmdLoginOutRes) Descriptor() ([]byte, []int) {
	return file_cs_login_proto_rawDescGZIP(), []int{3}
}

func (x *CsCmdLoginOutRes) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

// 创建账号请求
type CsCmdCreateAccountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User     string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Platform string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
}

func (x *CsCmdCreateAccountReq) Reset() {
	*x = CsCmdCreateAccountReq{}
	mi := &file_cs_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsCmdCreateAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCmdCreateAccountReq) ProtoMessage() {}

func (x *CsCmdCreateAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCmdCreateAccountReq.ProtoReflect.Descriptor instead.
func (*CsCmdCreateAccountReq) Descriptor() ([]byte, []int) {
	return file_cs_login_proto_rawDescGZIP(), []int{4}
}

func (x *CsCmdCreateAccountReq) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CsCmdCreateAccountReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

// 创建账号响应
type CsCmdCreateAccountRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User      string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Platform  string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	AccountId uint64 `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *CsCmdCreateAccountRes) Reset() {
	*x = CsCmdCreateAccountRes{}
	mi := &file_cs_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsCmdCreateAccountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCmdCreateAccountRes) ProtoMessage() {}

func (x *CsCmdCreateAccountRes) ProtoReflect() protoreflect.Message {
	mi := &file_cs_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCmdCreateAccountRes.ProtoReflect.Descriptor instead.
func (*CsCmdCreateAccountRes) Descriptor() ([]byte, []int) {
	return file_cs_login_proto_rawDescGZIP(), []int{5}
}

func (x *CsCmdCreateAccountRes) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CsCmdCreateAccountRes) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CsCmdCreateAccountRes) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

// 踢人通知
type CsCmdNtfKickAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint64 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Reason    int32  `protobuf:"varint,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *CsCmdNtfKickAccount) Reset() {
	*x = CsCmdNtfKickAccount{}
	mi := &file_cs_login_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsCmdNtfKickAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCmdNtfKickAccount) ProtoMessage() {}

func (x *CsCmdNtfKickAccount) ProtoReflect() protoreflect.Message {
	mi := &file_cs_login_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCmdNtfKickAccount.ProtoReflect.Descriptor instead.
func (*CsCmdNtfKickAccount) Descriptor() ([]byte, []int) {
	return file_cs_login_proto_rawDescGZIP(), []int{6}
}

func (x *CsCmdNtfKickAccount) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CsCmdNtfKickAccount) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

var File_cs_login_proto protoreflect.FileDescriptor

var file_cs_login_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x73, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x63, 0x73, 0x22, 0x3f, 0x0a, 0x0d, 0x43, 0x73, 0x43, 0x6d, 0x64, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0x5e, 0x0a, 0x0d, 0x43, 0x73, 0x43, 0x6d, 0x64, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x10, 0x43, 0x73, 0x43, 0x6d, 0x64, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x31, 0x0a, 0x10, 0x43, 0x73, 0x43, 0x6d,
	0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x15, 0x43,
	0x73, 0x43, 0x6d, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x22, 0x66, 0x0a, 0x15, 0x43, 0x73, 0x43, 0x6d, 0x64, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x1d, 0x0a,
	0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x13,
	0x43, 0x73, 0x43, 0x6d, 0x64, 0x4e, 0x74, 0x66, 0x4b, 0x69, 0x63, 0x6b, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x3b, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cs_login_proto_rawDescOnce sync.Once
	file_cs_login_proto_rawDescData = file_cs_login_proto_rawDesc
)

func file_cs_login_proto_rawDescGZIP() []byte {
	file_cs_login_proto_rawDescOnce.Do(func() {
		file_cs_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_cs_login_proto_rawDescData)
	})
	return file_cs_login_proto_rawDescData
}

var file_cs_login_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cs_login_proto_goTypes = []any{
	(*CsCmdLoginReq)(nil),         // 0: cs.CsCmdLoginReq
	(*CsCmdLoginRes)(nil),         // 1: cs.CsCmdLoginRes
	(*CsCmdLoginOutReq)(nil),      // 2: cs.CsCmdLoginOutReq
	(*CsCmdLoginOutRes)(nil),      // 3: cs.CsCmdLoginOutRes
	(*CsCmdCreateAccountReq)(nil), // 4: cs.CsCmdCreateAccountReq
	(*CsCmdCreateAccountRes)(nil), // 5: cs.CsCmdCreateAccountRes
	(*CsCmdNtfKickAccount)(nil),   // 6: cs.CsCmdNtfKickAccount
}
var file_cs_login_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cs_login_proto_init() }
func file_cs_login_proto_init() {
	if File_cs_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cs_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cs_login_proto_goTypes,
		DependencyIndexes: file_cs_login_proto_depIdxs,
		MessageInfos:      file_cs_login_proto_msgTypes,
	}.Build()
	File_cs_login_proto = out.File
	file_cs_login_proto_rawDesc = nil
	file_cs_login_proto_goTypes = nil
	file_cs_login_proto_depIdxs = nil
}
