// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.11
// source: cs_scene.proto

package cs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SCENE_ENTER_REQ = 201;      // 进入场景请求
type CsCmdSceneEnterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId   uint32 `protobuf:"varint,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	SceneId uint32 `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
}

func (x *CsCmdSceneEnterReq) Reset() {
	*x = CsCmdSceneEnterReq{}
	mi := &file_cs_scene_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsCmdSceneEnterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCmdSceneEnterReq) ProtoMessage() {}

func (x *CsCmdSceneEnterReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_scene_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCmdSceneEnterReq.ProtoReflect.Descriptor instead.
func (*CsCmdSceneEnterReq) Descriptor() ([]byte, []int) {
	return file_cs_scene_proto_rawDescGZIP(), []int{0}
}

func (x *CsCmdSceneEnterReq) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *CsCmdSceneEnterReq) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

// SCENE_ENTER_RES = 202;      // 进入场景响应
type CsCmdSceneEnterRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId   uint32 `protobuf:"varint,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	SceneId uint32 `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	PosX    uint32 `protobuf:"varint,3,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY    uint32 `protobuf:"varint,4,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
}

func (x *CsCmdSceneEnterRes) Reset() {
	*x = CsCmdSceneEnterRes{}
	mi := &file_cs_scene_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsCmdSceneEnterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCmdSceneEnterRes) ProtoMessage() {}

func (x *CsCmdSceneEnterRes) ProtoReflect() protoreflect.Message {
	mi := &file_cs_scene_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCmdSceneEnterRes.ProtoReflect.Descriptor instead.
func (*CsCmdSceneEnterRes) Descriptor() ([]byte, []int) {
	return file_cs_scene_proto_rawDescGZIP(), []int{1}
}

func (x *CsCmdSceneEnterRes) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *CsCmdSceneEnterRes) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *CsCmdSceneEnterRes) GetPosX() uint32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *CsCmdSceneEnterRes) GetPosY() uint32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

// SCENE_LEAVE_REQ = 203;      // 离开场景请求
type CsCmdSceneLeaveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId   uint32 `protobuf:"varint,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	SceneId uint32 `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
}

func (x *CsCmdSceneLeaveReq) Reset() {
	*x = CsCmdSceneLeaveReq{}
	mi := &file_cs_scene_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsCmdSceneLeaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCmdSceneLeaveReq) ProtoMessage() {}

func (x *CsCmdSceneLeaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_scene_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCmdSceneLeaveReq.ProtoReflect.Descriptor instead.
func (*CsCmdSceneLeaveReq) Descriptor() ([]byte, []int) {
	return file_cs_scene_proto_rawDescGZIP(), []int{2}
}

func (x *CsCmdSceneLeaveReq) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *CsCmdSceneLeaveReq) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

// SCENE_LEAVE_RES = 204;      // 离开场景响应
type CsCmdSceneLeaveRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId   uint32 `protobuf:"varint,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	SceneId uint32 `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
}

func (x *CsCmdSceneLeaveRes) Reset() {
	*x = CsCmdSceneLeaveRes{}
	mi := &file_cs_scene_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsCmdSceneLeaveRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCmdSceneLeaveRes) ProtoMessage() {}

func (x *CsCmdSceneLeaveRes) ProtoReflect() protoreflect.Message {
	mi := &file_cs_scene_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCmdSceneLeaveRes.ProtoReflect.Descriptor instead.
func (*CsCmdSceneLeaveRes) Descriptor() ([]byte, []int) {
	return file_cs_scene_proto_rawDescGZIP(), []int{3}
}

func (x *CsCmdSceneLeaveRes) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *CsCmdSceneLeaveRes) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

// SCENE_NTF_ENTER = 205;      // 通知进入场景
type CsCmdSceneNtfEnter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId []uint64 `protobuf:"varint,1,rep,packed,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	MapId     uint32   `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	SceneId   uint32   `protobuf:"varint,3,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	X         uint32   `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y         uint32   `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *CsCmdSceneNtfEnter) Reset() {
	*x = CsCmdSceneNtfEnter{}
	mi := &file_cs_scene_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsCmdSceneNtfEnter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCmdSceneNtfEnter) ProtoMessage() {}

func (x *CsCmdSceneNtfEnter) ProtoReflect() protoreflect.Message {
	mi := &file_cs_scene_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCmdSceneNtfEnter.ProtoReflect.Descriptor instead.
func (*CsCmdSceneNtfEnter) Descriptor() ([]byte, []int) {
	return file_cs_scene_proto_rawDescGZIP(), []int{4}
}

func (x *CsCmdSceneNtfEnter) GetAccountId() []uint64 {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *CsCmdSceneNtfEnter) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *CsCmdSceneNtfEnter) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *CsCmdSceneNtfEnter) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CsCmdSceneNtfEnter) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// SCENE_NTF_LEAVE = 206;      // 通知离开场景
type CsCmdSceneNtfLeave struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId []uint64 `protobuf:"varint,1,rep,packed,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	MapId     uint32   `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	SceneId   uint32   `protobuf:"varint,3,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
}

func (x *CsCmdSceneNtfLeave) Reset() {
	*x = CsCmdSceneNtfLeave{}
	mi := &file_cs_scene_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsCmdSceneNtfLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCmdSceneNtfLeave) ProtoMessage() {}

func (x *CsCmdSceneNtfLeave) ProtoReflect() protoreflect.Message {
	mi := &file_cs_scene_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCmdSceneNtfLeave.ProtoReflect.Descriptor instead.
func (*CsCmdSceneNtfLeave) Descriptor() ([]byte, []int) {
	return file_cs_scene_proto_rawDescGZIP(), []int{5}
}

func (x *CsCmdSceneNtfLeave) GetAccountId() []uint64 {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *CsCmdSceneNtfLeave) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *CsCmdSceneNtfLeave) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

// SCENE_NTF_MOVE = 207;       // 通知移动
type CsCmdSceneNtfMove struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId uint64 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	MapId     uint32 `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	SceneId   uint32 `protobuf:"varint,3,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	X         uint32 `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y         uint32 `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	OldX      uint32 `protobuf:"varint,6,opt,name=old_x,json=oldX,proto3" json:"old_x,omitempty"`
	OldY      uint32 `protobuf:"varint,7,opt,name=old_y,json=oldY,proto3" json:"old_y,omitempty"`
}

func (x *CsCmdSceneNtfMove) Reset() {
	*x = CsCmdSceneNtfMove{}
	mi := &file_cs_scene_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsCmdSceneNtfMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCmdSceneNtfMove) ProtoMessage() {}

func (x *CsCmdSceneNtfMove) ProtoReflect() protoreflect.Message {
	mi := &file_cs_scene_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCmdSceneNtfMove.ProtoReflect.Descriptor instead.
func (*CsCmdSceneNtfMove) Descriptor() ([]byte, []int) {
	return file_cs_scene_proto_rawDescGZIP(), []int{6}
}

func (x *CsCmdSceneNtfMove) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CsCmdSceneNtfMove) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *CsCmdSceneNtfMove) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *CsCmdSceneNtfMove) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CsCmdSceneNtfMove) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *CsCmdSceneNtfMove) GetOldX() uint32 {
	if x != nil {
		return x.OldX
	}
	return 0
}

func (x *CsCmdSceneNtfMove) GetOldY() uint32 {
	if x != nil {
		return x.OldY
	}
	return 0
}

// SCENE_MOVE_REQ = 208;       // 移动
type CsCmdSceneMoveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId   uint32 `protobuf:"varint,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	SceneId uint32 `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	PosX    uint32 `protobuf:"varint,3,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY    uint32 `protobuf:"varint,4,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
}

func (x *CsCmdSceneMoveReq) Reset() {
	*x = CsCmdSceneMoveReq{}
	mi := &file_cs_scene_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsCmdSceneMoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCmdSceneMoveReq) ProtoMessage() {}

func (x *CsCmdSceneMoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_cs_scene_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCmdSceneMoveReq.ProtoReflect.Descriptor instead.
func (*CsCmdSceneMoveReq) Descriptor() ([]byte, []int) {
	return file_cs_scene_proto_rawDescGZIP(), []int{7}
}

func (x *CsCmdSceneMoveReq) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *CsCmdSceneMoveReq) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *CsCmdSceneMoveReq) GetPosX() uint32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *CsCmdSceneMoveReq) GetPosY() uint32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

// SCENE_MOVE_RES = 209;       // 移动
type CsCmdSceneMoveRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId   uint32 `protobuf:"varint,1,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	SceneId uint32 `protobuf:"varint,2,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	PosX    uint32 `protobuf:"varint,3,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY    uint32 `protobuf:"varint,4,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
}

func (x *CsCmdSceneMoveRes) Reset() {
	*x = CsCmdSceneMoveRes{}
	mi := &file_cs_scene_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CsCmdSceneMoveRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CsCmdSceneMoveRes) ProtoMessage() {}

func (x *CsCmdSceneMoveRes) ProtoReflect() protoreflect.Message {
	mi := &file_cs_scene_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CsCmdSceneMoveRes.ProtoReflect.Descriptor instead.
func (*CsCmdSceneMoveRes) Descriptor() ([]byte, []int) {
	return file_cs_scene_proto_rawDescGZIP(), []int{8}
}

func (x *CsCmdSceneMoveRes) GetMapId() uint32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *CsCmdSceneMoveRes) GetSceneId() uint32 {
	if x != nil {
		return x.SceneId
	}
	return 0
}

func (x *CsCmdSceneMoveRes) GetPosX() uint32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *CsCmdSceneMoveRes) GetPosY() uint32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

var File_cs_scene_proto protoreflect.FileDescriptor

var file_cs_scene_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x73, 0x5f, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x63, 0x73, 0x22, 0x46, 0x0a, 0x12, 0x43, 0x73, 0x43, 0x6d, 0x64, 0x53, 0x63, 0x65,
	0x6e, 0x65, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x70, 0x0a, 0x12,
	0x43, 0x73, 0x43, 0x6d, 0x64, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x63, 0x65,
	0x6e, 0x65, 0x49, 0x64, 0x12, 0x13, 0x0a, 0x05, 0x70, 0x6f, 0x73, 0x5f, 0x78, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x73, 0x58, 0x12, 0x13, 0x0a, 0x05, 0x70, 0x6f, 0x73,
	0x5f, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x73, 0x59, 0x22, 0x46,
	0x0a, 0x12, 0x43, 0x73, 0x43, 0x6d, 0x64, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4c, 0x65, 0x61, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73,
	0x63, 0x65, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73,
	0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x12, 0x43, 0x73, 0x43, 0x6d, 0x64, 0x53,
	0x63, 0x65, 0x6e, 0x65, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x12, 0x15, 0x0a, 0x06,
	0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61,
	0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x22, 0x81,
	0x01, 0x0a, 0x12, 0x43, 0x73, 0x43, 0x6d, 0x64, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4e, 0x74, 0x66,
	0x45, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73,
	0x63, 0x65, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73,
	0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x01, 0x79, 0x22, 0x65, 0x0a, 0x12, 0x43, 0x73, 0x43, 0x6d, 0x64, 0x53, 0x63, 0x65, 0x6e, 0x65,
	0x4e, 0x74, 0x66, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6d, 0x61, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x22, 0xaa, 0x01, 0x0a, 0x11, 0x43, 0x73,
	0x43, 0x6d, 0x64, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x4e, 0x74, 0x66, 0x4d, 0x6f, 0x76, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x15,
	0x0a, 0x06, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x79, 0x12, 0x13, 0x0a, 0x05,
	0x6f, 0x6c, 0x64, 0x5f, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6f, 0x6c, 0x64,
	0x58, 0x12, 0x13, 0x0a, 0x05, 0x6f, 0x6c, 0x64, 0x5f, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x6f, 0x6c, 0x64, 0x59, 0x22, 0x6f, 0x0a, 0x11, 0x43, 0x73, 0x43, 0x6d, 0x64, 0x53,
	0x63, 0x65, 0x6e, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x6d,
	0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61, 0x70,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x13, 0x0a,
	0x05, 0x70, 0x6f, 0x73, 0x5f, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f,
	0x73, 0x58, 0x12, 0x13, 0x0a, 0x05, 0x70, 0x6f, 0x73, 0x5f, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x70, 0x6f, 0x73, 0x59, 0x22, 0x6f, 0x0a, 0x11, 0x43, 0x73, 0x43, 0x6d, 0x64,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x12, 0x15, 0x0a, 0x06,
	0x6d, 0x61, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6d, 0x61,
	0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x63, 0x65, 0x6e, 0x65, 0x49, 0x64, 0x12, 0x13,
	0x0a, 0x05, 0x70, 0x6f, 0x73, 0x5f, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70,
	0x6f, 0x73, 0x58, 0x12, 0x13, 0x0a, 0x05, 0x70, 0x6f, 0x73, 0x5f, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x73, 0x59, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x63,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cs_scene_proto_rawDescOnce sync.Once
	file_cs_scene_proto_rawDescData = file_cs_scene_proto_rawDesc
)

func file_cs_scene_proto_rawDescGZIP() []byte {
	file_cs_scene_proto_rawDescOnce.Do(func() {
		file_cs_scene_proto_rawDescData = protoimpl.X.CompressGZIP(file_cs_scene_proto_rawDescData)
	})
	return file_cs_scene_proto_rawDescData
}

var file_cs_scene_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cs_scene_proto_goTypes = []any{
	(*CsCmdSceneEnterReq)(nil), // 0: cs.CsCmdSceneEnterReq
	(*CsCmdSceneEnterRes)(nil), // 1: cs.CsCmdSceneEnterRes
	(*CsCmdSceneLeaveReq)(nil), // 2: cs.CsCmdSceneLeaveReq
	(*CsCmdSceneLeaveRes)(nil), // 3: cs.CsCmdSceneLeaveRes
	(*CsCmdSceneNtfEnter)(nil), // 4: cs.CsCmdSceneNtfEnter
	(*CsCmdSceneNtfLeave)(nil), // 5: cs.CsCmdSceneNtfLeave
	(*CsCmdSceneNtfMove)(nil),  // 6: cs.CsCmdSceneNtfMove
	(*CsCmdSceneMoveReq)(nil),  // 7: cs.CsCmdSceneMoveReq
	(*CsCmdSceneMoveRes)(nil),  // 8: cs.CsCmdSceneMoveRes
}
var file_cs_scene_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cs_scene_proto_init() }
func file_cs_scene_proto_init() {
	if File_cs_scene_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cs_scene_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cs_scene_proto_goTypes,
		DependencyIndexes: file_cs_scene_proto_depIdxs,
		MessageInfos:      file_cs_scene_proto_msgTypes,
	}.Build()
	File_cs_scene_proto = out.File
	file_cs_scene_proto_rawDesc = nil
	file_cs_scene_proto_goTypes = nil
	file_cs_scene_proto_depIdxs = nil
}
