name: Lint

on:
  push:
    branches:
      - master
      - dev
      - 1.x
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
      - dev
      - 1.x
    paths-ignore:
      - '**.md'

jobs:
  golangci:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
#          - windows-latest
    name: Golangci-Lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17'
      - uses: actions/checkout@v3
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          args: -E gofumpt -E gocritic -E misspell -E revive -E godot
