// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.11
// source: ss_cmd.proto

package ss

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 不必带SS_CMD，因为这个文件就是定义SS_CMD的，会自动加上ss前缀
type SS_CMD int32

const (
	SS_CMD_UNKNOWN             SS_CMD = 0
	SS_CMD_KICK_ACCOUNT_REQ    SS_CMD = 1
	SS_CMD_KICK_ACCOUNT_RES    SS_CMD = 2
	SS_CMD_REGISTER_SERVER_REQ SS_CMD = 3
	SS_CMD_REGISTER_SERVER_RES SS_CMD = 4
)

// Enum value maps for SS_CMD.
var (
	SS_CMD_name = map[int32]string{
		0: "UNKNOWN",
		1: "KICK_ACCOUNT_REQ",
		2: "KICK_ACCOUNT_RES",
		3: "REGISTER_SERVER_REQ",
		4: "REGISTER_SERVER_RES",
	}
	SS_CMD_value = map[string]int32{
		"UNKNOWN":             0,
		"KICK_ACCOUNT_REQ":    1,
		"KICK_ACCOUNT_RES":    2,
		"REGISTER_SERVER_REQ": 3,
		"REGISTER_SERVER_RES": 4,
	}
)

func (x SS_CMD) Enum() *SS_CMD {
	p := new(SS_CMD)
	*p = x
	return p
}

func (x SS_CMD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SS_CMD) Descriptor() protoreflect.EnumDescriptor {
	return file_ss_cmd_proto_enumTypes[0].Descriptor()
}

func (SS_CMD) Type() protoreflect.EnumType {
	return &file_ss_cmd_proto_enumTypes[0]
}

func (x SS_CMD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SS_CMD.Descriptor instead.
func (SS_CMD) EnumDescriptor() ([]byte, []int) {
	return file_ss_cmd_proto_rawDescGZIP(), []int{0}
}

var File_ss_cmd_proto protoreflect.FileDescriptor

var file_ss_cmd_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x73, 0x5f, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x73, 0x73, 0x2a, 0x73, 0x0a, 0x06, 0x53, 0x53, 0x5f, 0x43, 0x4d, 0x44, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4b, 0x49, 0x43,
	0x4b, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x01, 0x12,
	0x14, 0x0a, 0x10, 0x4b, 0x49, 0x43, 0x4b, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f,
	0x52, 0x45, 0x53, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45,
	0x52, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45, 0x52, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x03, 0x12, 0x17,
	0x0a, 0x13, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x45,
	0x52, 0x5f, 0x52, 0x45, 0x53, 0x10, 0x04, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x73, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ss_cmd_proto_rawDescOnce sync.Once
	file_ss_cmd_proto_rawDescData = file_ss_cmd_proto_rawDesc
)

func file_ss_cmd_proto_rawDescGZIP() []byte {
	file_ss_cmd_proto_rawDescOnce.Do(func() {
		file_ss_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(file_ss_cmd_proto_rawDescData)
	})
	return file_ss_cmd_proto_rawDescData
}

var file_ss_cmd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ss_cmd_proto_goTypes = []any{
	(SS_CMD)(0), // 0: ss.SS_CMD
}
var file_ss_cmd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ss_cmd_proto_init() }
func file_ss_cmd_proto_init() {
	if File_ss_cmd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ss_cmd_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ss_cmd_proto_goTypes,
		DependencyIndexes: file_ss_cmd_proto_depIdxs,
		EnumInfos:         file_ss_cmd_proto_enumTypes,
	}.Build()
	File_ss_cmd_proto = out.File
	file_ss_cmd_proto_rawDesc = nil
	file_ss_cmd_proto_goTypes = nil
	file_ss_cmd_proto_depIdxs = nil
}
