// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.21.11
// source: ss_common.proto

package ss

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息头
type SsHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cmd            int32 `protobuf:"varint,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Seq            int32 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Ret            int32 `protobuf:"varint,3,opt,name=ret,proto3" json:"ret,omitempty"`
	ServerId       int32 `protobuf:"varint,4,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	TargetServerId int32 `protobuf:"varint,5,opt,name=target_server_id,json=targetServerId,proto3" json:"target_server_id,omitempty"`
}

func (x *SsHead) Reset() {
	*x = SsHead{}
	mi := &file_ss_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SsHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SsHead) ProtoMessage() {}

func (x *SsHead) ProtoReflect() protoreflect.Message {
	mi := &file_ss_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SsHead.ProtoReflect.Descriptor instead.
func (*SsHead) Descriptor() ([]byte, []int) {
	return file_ss_common_proto_rawDescGZIP(), []int{0}
}

func (x *SsHead) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *SsHead) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SsHead) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *SsHead) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *SsHead) GetTargetServerId() int32 {
	if x != nil {
		return x.TargetServerId
	}
	return 0
}

// 消息包
type SsPkg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *SsHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Body []byte  `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *SsPkg) Reset() {
	*x = SsPkg{}
	mi := &file_ss_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SsPkg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SsPkg) ProtoMessage() {}

func (x *SsPkg) ProtoReflect() protoreflect.Message {
	mi := &file_ss_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SsPkg.ProtoReflect.Descriptor instead.
func (*SsPkg) Descriptor() ([]byte, []int) {
	return file_ss_common_proto_rawDescGZIP(), []int{1}
}

func (x *SsPkg) GetHead() *SsHead {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *SsPkg) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_ss_common_proto protoreflect.FileDescriptor

var file_ss_common_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x73, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x73, 0x73, 0x22, 0x85, 0x01, 0x0a, 0x06, 0x53, 0x73, 0x48, 0x65, 0x61, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63,
	0x6d, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x73, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3b, 0x0a,
	0x05, 0x53, 0x73, 0x50, 0x6b, 0x67, 0x12, 0x1e, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73, 0x73, 0x2e, 0x53, 0x73, 0x48, 0x65, 0x61, 0x64,
	0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f,
	0x3b, 0x73, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ss_common_proto_rawDescOnce sync.Once
	file_ss_common_proto_rawDescData = file_ss_common_proto_rawDesc
)

func file_ss_common_proto_rawDescGZIP() []byte {
	file_ss_common_proto_rawDescOnce.Do(func() {
		file_ss_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_ss_common_proto_rawDescData)
	})
	return file_ss_common_proto_rawDescData
}

var file_ss_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ss_common_proto_goTypes = []any{
	(*SsHead)(nil), // 0: ss.SsHead
	(*SsPkg)(nil),  // 1: ss.SsPkg
}
var file_ss_common_proto_depIdxs = []int32{
	0, // 0: ss.SsPkg.head:type_name -> ss.SsHead
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ss_common_proto_init() }
func file_ss_common_proto_init() {
	if File_ss_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ss_common_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ss_common_proto_goTypes,
		DependencyIndexes: file_ss_common_proto_depIdxs,
		MessageInfos:      file_ss_common_proto_msgTypes,
	}.Build()
	File_ss_common_proto = out.File
	file_ss_common_proto_rawDesc = nil
	file_ss_common_proto_goTypes = nil
	file_ss_common_proto_depIdxs = nil
}
